import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SpaceBackground from "./App/animation/animation";
import Navbar from "./App/Components/Navbar/Navbar";
import NavAnimation from "./App/NavAnimation/NavAnimation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#301403]`}
      >
        {/* 🎇 Background Fixed Space Animation */}
        <div className="fixed inset-0 -z-10">
          <SpaceBackground />
        </div>
        <div>
          <Navbar></Navbar>
        </div>
        <NavAnimation></NavAnimation>
        {/* 🌐 Main Page Content */}
        <main className="relative z-10">{children}</main>
      </body>
    </html>
  );
}
